# Generated by Django 3.2.13 on 2022-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220506_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.URLField(blank=True, null=True, verbose_name='商品ページ'),
        ),
    ]
