# Generated by Django 3.2.13 on 2022-05-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='出版社名'),
        ),
    ]
