# Generated by Django 3.2.13 on 2022-06-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('sex', models.CharField(max_length=1, verbose_name='性別')),
            ],
            options={
                'db_table': 'horses',
            },
        ),
    ]
