# Generated by Django 3.2.13 on 2022-06-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keiba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='レース名')),
                ('grade', models.CharField(max_length=10, null=True, verbose_name='格')),
                ('terms', models.CharField(max_length=255, null=True, verbose_name='条件')),
            ],
            options={
                'db_table': 'races',
            },
        ),
    ]
